name: Demo
options:
  bundleIdPrefix: io.datagrail.consent
  deploymentTarget:
    iOS: "15.0"
targets:
  Demo:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Demo
        name: Demo
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.datagrail.consent.demo
      SWIFT_VERSION: "5.0"
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: "1,2"
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: DataGrailConsent
packages:
  DataGrailConsent:
    path: ../
