name: pre-commit

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: andrewaylett/pre-commit-action@04b53a11774a43f33aa4b4419106b445a0b8dea1 # v4.5.1-27
